version: ’2’
services:
  mqtt:
    container_name: "mqtt"
    image: toke/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  web:
    container_name: "web"
    image: kyma/docker-nginx
    ports:
      - 80:80
    volumes:
      - ~/www:/var/www
